Starting Debug for lxc1-0
Running Command /home/vignesh/Desktop/PLCs/awlsim-0.42/tests/run.sh -e 1 --node 1 /home/vignesh/Desktop/PLCs/awlsim-0.42/tests/modbus/simple_client_server/sfb102_client.awl
6 (process ID) old priority 0, new priority 10
=== Running tests with 'python3'
Running test 'sfb102_client.awl' with 'python3' ... Traceback (most recent call last):
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/tests/../awlsim-cli", line 625, in <module>
    sys.exit(main())
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/tests/../awlsim-cli", line 622, in main
    return run(inputFile,node_id,conn_type)
  File "/home/vignesh/Desktop/PLCs/awlsim-0.42/tests/../awlsim-cli", line 230, in run
    lines = [line.rstrip('\n') for line in open(conf_file)]			
IOError: [Errno 2] No such file or directory: '/home/vignesh/Desktop/PLCs/awlsim-0.42/conf/PLC_Config/hosts'
=== TEST FAILED ===
Test 'sfb102_client.awl' FAILED
